# Generated by Django 5.0.4 on 2024-04-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='adviser_avatars/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='/default_avatar.png', null=True, upload_to='student_avatars/'),
        ),
    ]
